### ISSUE TITLE
`Call-service API error.  Error Message: extra keys not allowed @ data['size']`

### ISSUE THREAD

**Issue by milbr** [pdong/node-contrib-inovelli-status-manager#11]
Getting this error from the service call node taking input from inovelli-status-manager node:

`Call-service API error.  Error Message: extra keys not allowed @ data['size']`

The error started when I switched to the new OpenZWave (beta), which has some changes on set_config_parameter
https://www.home-assistant.io/integrations/ozw/#service-ozwset_config_parameter

**Comment by cree8** [comment]
Looks like this node does not work with the new OZW daemon due to the output. I have the same issue. 'size' is not a valid attribute for ozw.set_config_parameter. The node logic will need to be updated.
In the mean while I was able to use a change node to suppress (delete) the `size` attribute from the flow @milbr

**Comment by pdong** [comment]
Thank you for the report @milbr.  I haven't updated to OpenZWave beta yet but I'll take a look into it and see if I can't get this fixed.

@cree8 is correct you could add a function node in between your service and do something like


```
delete msg.payload.data.size;

return msg;
```

Which would fix the issue for now.  Let me do some testing to see if omitting size works for current OpenZWave users and if we can't just delete it completely.

**Comment by pdong** [comment]
I tested with size stripped out and it still worked so I went ahead and published a fix for it (version 0.0.12).  Thanks again for reporting!

**Comment by grilledbacon32** [comment]
Hi, I'm pretty new with all of this stuff and see you fixed this issue but I'm only seeing version 0.0.11 in Node Red. Is it still being published or am I missing something. Sorry for the noob question! Thank you!

**Comment by pdong** [comment]
@grilledbacon32 Thanks for letting me know.  When the package is published to npm, Node-RED picks it up via some search API.  For some reason it isn't detecting that the version updated even though the package was successfully published (you can go here: https://flows.nodered.org/node/node-contrib-inovelli-status-manager and then click on npm and see that I published another version to try to get Node-RED to pick it up).  I'm going to ask in Node-RED slack and see if there is an issue on their end.

**Comment by pdong** [comment]
@grilledbacon32 Sorry about that.  The package should be published now.  I missed the update to Node-RED in April that requires manual refreshes/publishing of packages.  Should be good to go now; let me know if there are any issues.  Thanks again for letting me know about this

**Comment by grilledbacon32** [comment]
> @grilledbacon32 Sorry about that. The package should be published now. I missed the update to Node-RED in April that requires manual refreshes/publishing of packages. Should be good to go now; let me know if there are any issues. Thanks again for letting me know about this

Thank you!! I'm seeing it now!
