### ISSUE TITLE
Allow 0 (Red) as possible color

### ISSUE THREAD

**Issue by kreene1987** [pdong/node-contrib-inovelli-status-manager#14]
Cross-posting from community.inovelli.com. 

Possible colors are 0 to 255 but currently only 1-255 are allowed on the color band.

Please add ability to pass 0 as a color (adapt calculation to add 0 at end).

**Comment by kreene1987** [comment]
Bueller?

**Comment by pdong** [comment]
Sorry thanks for the contribution.  Merged and will publish a new version soon
