### ISSUE TITLE
ZwaveJS compatibility

### ISSUE THREAD

**Issue by DeltaNu1142** [pdong/node-contrib-inovelli-status-manager#18]
zwave_js.set_config_parameter has been added to Home Assistant, opening the door for this node to work with ZwaveJS.

**Comment by ryanjohnsontv** [comment]
I have a fork of this that supports Z-Wave JS, however there seems to be an issue with the set_config_parameter with the Home Assistant ZWave-JS integration that stops it from accepting values outside of its presets (limited color range). This should be updated in 2021.3.5

**Comment by pdong** [comment]
zwave js now has a `bulk_set_partial_config_parameters` that you can use.  If you're using z-wave js you don't want to pass node_id.  

I should add an example flow for this an annotation around the node id input.

**Comment by pdong** [comment]
I fixed the examples for use with zwavejs and deprecated node_id
