### ISSUE TITLE
UI issue with switch type selector

### ISSUE THREAD

**Issue by cbulock** [pdong/node-contrib-inovelli-status-manager#3]
I am happy to see the on/off  or dimmer selector being merged in, but the UI doesn't look to be working

<img width="473" alt="Screenshot 2020-01-12 15 55 48" src="https://user-images.githubusercontent.com/176519/72225509-23a8a000-3554-11ea-98d4-8efa0bf75be9.png">

There are two radio buttons, but they aren't lined up with the options, and if you select the second radio button, both end up selected.

<img width="483" alt="Screenshot 2020-01-12 15 55 56" src="https://user-images.githubusercontent.com/176519/72225510-24413680-3554-11ea-8168-98e8aac4e6e8.png">

**Comment by jasonwilk** [comment]
@pdong THANK YOU for merging in the pull request. Any chance you would be able to look at this issue?

**Comment by jasonwilk** [comment]
Or @smugleafdev , this might be something you could fix?

**Comment by pdong** [comment]
Should be fixed by #4 .  I didn't have time to look into how radio inputs are usually implemented in Node-RED but it looks like the radio wasn't working anyway so we'll have to deal w/ a select for now.  Looks like the param wasn't working anyway so I've fixed that as well.  Published as 0.0.9 LMK if that works for you guys (I don't have dimmer switches so I cannot confirm).

**Comment by jasonwilk** [comment]
Thanks, @pdong . I'll update as soon as it hits and report back.

**Comment by smugleafdev** [comment]
Sorry about the UI issue! That's what I get for not testing it locally first. The Switch type seems to be working much better, but the calculation is a bit off.

Solid is solid, but slow blink is fast, fast is pulse, and pulse is slow. Also, colors are off. Red ends up pinkish, and dark blue ends up cyanish. I'll see if I can figure out why that is tomorrow.

**Comment by cbulock** [comment]
@smugleafdev The reason the effects are not correct is due to the dimmer using different values for them as well. Basically, they added "chase" (which is pretty cool) as value 2 and that shifts the other effects over one.

For the on/off switch, these are the effects:
0: off
1: solid
2: fast blink
3: slow blink
4: pulse

For the dimmer, it's these values:
0: off
1: solid
2: chase
3: fast blink
4: slow blink
5: pulse

**Comment by jasonwilk** [comment]
@smugleafdev @pdong I have two dimmers installed. Let me know if I can be of any assistance. I can test/send raw svc commands outside of Node Red if needed to see what happens.

**Comment by jasonwilk** [comment]
@smugleafdev I also thought this might help. I saw it posted in the Inovelli forums. 

https://nathanfiscus.github.io/inovelli-notification-calc/

**Comment by pdong** [comment]
Thanks @cbulock 👍 I've updated the node so that when you switch types it will reset the effect field and now Chase is supported for dimmer switches.  If you guys run into any other problems please open another issue so we can track.  Thanks
