### ISSUE TITLE
Display Type values not persisting

### ISSUE THREAD

**Issue by jasonwilk** [pdong/node-contrib-inovelli-status-manager#6]
I've tested this with both the dimmer and the switch. For some reason when choosing a Display Type and saving it, the Display Type value does not persist. I can set it and it will sometimes work. But it generally reverts back to `off`. 

I set the value as it appears below. Saved it and depolyed it.
<img width="580" alt="Screenshot 2020-01-13 23 45 35" src="https://user-images.githubusercontent.com/384488/72317486-13c9b280-365f-11ea-906a-21a1be061a2d.png">

After deploying, I opened it back up and it appeared like this in the interface. 
<img width="505" alt="Screenshot 2020-01-13 23 45 46" src="https://user-images.githubusercontent.com/384488/72317487-13c9b280-365f-11ea-8b15-622742177a9a.png">

**Comment by jasonwilk** [comment]
@pdong Thank you for fixing the values with 0.0.10. For some reason it introduced a new bug. Thank you for your work on this!

**Comment by pdong** [comment]
I will take a peek. I'm guessing the code to reset runs when the panel is first loaded. It should be saving correctly if you change it but this is pretty annoying if you're going in to change another value and don't notice this resetting.
