### ISSUE TITLE
Cant lower brightness enough. Slider hops to zero. 

### ISSUE THREAD

**Issue by plainslice** [pdong/node-contrib-inovelli-status-manager#8]
Hey,

Not sure if this is due to a bug or just a limitation of the hardware. 

If I try to lower the brightness to a minimal level, the slider will stop at the location shown in the attached picture. This brightness is still too bright to have it in a bedroom, as it will still glow pretty bright. If I try to lower it a hair more (just slightly less bright would be ideal), it jumps to zero. There is no way to lower it below this hard stop. 

Ideally, Id like to be able to set it at the same brightness level that the switch glows by default but this doesnt seem currently possible due to the above issue. Its lowest setting Im able to set it to is still much brighter then the default blue glow. 

[image](https://user-images.githubusercontent.com/25411305/78212004-d0b3fa00-746b-11ea-9756-085c5288bcae.png)

This thing is amazing btw, greatly appreciate your hard work!

**Comment by pdong** [comment]
@pizzapants Unfortunately the brightness value only supports values from 0 to 10.  You can try choosing a darker blue and the lower setting (1).  I'm not sure if this is a software limitation on Inovelli's side or if they could support more brightness levels in the future.  For now that isn't anything we can do.  I'll keep an eye on the switch firmware to see if anything changes regarding brightness though.
