### ISSUE TITLE
Add support for pulling list of zwave entities from Home Assistant

### ISSUE THREAD

**Issue by neilenns** [pdong/node-contrib-inovelli-status-manager#9]
It'd be nice if the node could get the list of Inovelli switches registered with a Home Assistant server instead of having to manually type the node ID in. I realize this would make the node tied to Home Assistant, so maybe two nodes are necessary.

https://github.com/zachowj/node-red-contrib-home-assistant-websocket/tree/dev/nodes/current-state (or somewhere in the repo generally) likely has the necessary example of how to do this.

**Comment by pdong** [comment]
@danecreekphotography  The entity_id that HA uses is different than the ID (zwave ID number) we need to send to `set_config_parameter` which might make this tricky.  If you can figure it out I'd welcome a pull request though.  In the meanwhile one workaround that you can play around with is setting up subflows that call `zwave.set_config_parameter`, leave the ID field blank then have 

example:

```
[
    {
        "id": "86e0312b.079b8",
        "type": "subflow",
        "name": "Rear Porch",
        "info": "",
        "category": "",
        "in": [
            {
                "x": 145,
                "y": 150,
                "wires": [
                    {
                        "id": "81c6b427.283418"
                    }
                ]
            }
        ],
        "out": [],
        "env": [],
        "color": "#DDAA99"
    },
    {
        "id": "81c6b427.283418",
        "type": "api-call-service",
        "z": "86e0312b.079b8",
        "name": "Rear Porch",
        "server": "cdeacb62.bfde18",
        "version": 1,
        "service_domain": "zwave",
        "service": "set_config_parameter",
        "entityId": "",
        "data": "{\"node_id\":7}",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "",
        "output_location_type": "none",
        "mustacheAltTags": false,
        "x": 370,
        "y": 150,
        "wires": [
            []
        ]
    }
]
```

Then you can wire the status manager into this subflow which will call the zwave service with the correct node_id.  

![image](https://user-images.githubusercontent.com/5158502/84980739-b4793e00-b0e7-11ea-969e-46a88a3c8f3a.png)

I have a subflow set up with all my switches and I do this:

![image](https://user-images.githubusercontent.com/5158502/84980780-d07cdf80-b0e7-11ea-9ce2-a6f031734562.png)
